# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FCCore' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FCCore
  pod 'FMDB'
  pod 'FMDB/SQLCipher'    # FMDB with SQLCipher

  target 'FCCoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
